### ISSUE TITLE
Allow to configure GLX_RGBA

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#62]
Old pugl used to have GLX_RGBA, but this is not available anymore.
Perhaps not useful by default, I have been using the new pugl for a while and only noticed it now. But would be nice to allow it.
So this is a request to make that configurable.

For a little background, there is at least 1 tool that makes use of it.

This is with current pugl (note how the background color of the welcome dialog is flat)

![Screenshot_20211008_225815](https://user-images.githubusercontent.com/1334853/136629028-8ed65946-22ee-43f4-8ee5-ead7b9cef87c.png)

And now with RGBA active, we can see a little gradient on the top of the dialog

![Screenshot_20211008_225909](https://user-images.githubusercontent.com/1334853/136629100-940a9cab-ba98-4350-a167-91802068bb25.png)

The same gradient is also present on the top bar and menus

![Screenshot_20211008_225956](https://user-images.githubusercontent.com/1334853/136629397-97ffc0d7-021d-49cf-83df-845c9304fc13.png)

**Comment by drobilla** [comment]
I don't get what `GLX_RGBA` does.  It's not in the documentation as far as I can tell, and everything else in the attribute list is a key/value thing.  `GLX_RGBA` is plopped weirdly at the beginning with no value though.

**Comment by falkTX** [comment]
yeah, I think something here is not quite right.
it also does not work on nvidia cards, only on intel and amd. but it does make things draw differently for some reason.

so ignore this for now, if I find any useful info I will let you know.

**Comment by drobilla** [comment]
Yeah, it's weird.  This is why I don't want to blindly add this, not only does it seem to not fit in with how everything else works, it seems like a sketchy driver mine field.  We need to figure out how to make things work properly though.

I did find this: "The value GLX_RGBA tells GLX that the color depth shall be true color. The depth buffer shall be 24 bits deep, and a double buffer shall be used."

Do you have things set up so that all of that is true?  In particular, I think PUGL_DEPTH_BITS is zero by default.  Maybe if you set that you'll get the same behaviour.

**Comment by drobilla** [comment]
After further tinkering with OpenGL flags recently, I'm pretty sure the above is right, i.e., if you want alpha, set PUGL_DEPTH_BITS accordingly.  Using the defaults here isn't a great idea, applications should specify every hint that is relevant to them explicitly.

I haven't reproduced this exact issue, but on every system I have available to test on, setting up alpha explicitly seems to work as expected, so I'll close this for now.  Feel free to reopen if the issue persists when all the relevant GL flags are set explicitly though.

**Comment by falkTX** [comment]
all fine, I think my approach here was wrong anyway.
