### ISSUE TITLE
Add API to report parent window / desktop scale factor

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#65]
Scale factor is a tricky business sometimes, IMO pugl should be able to report this to UIs

When scale != 1 we often want to scale up the UI size to match what the host or desktop uses.
I found with DPF that this needs to be done for each UI, I have methods to auto-scale UIs but in order to work proper most UIs need custom code.

Feel free to grab the code from https://github.com/DISTRHO/DPF/blob/develop/dgl/src/pugl.cpp#L207 which already handles this for all pugl supported platforms.

**Comment by drobilla** [comment]
Why parent window?

**Comment by falkTX** [comment]
I mean the one we are meant to embed into.
So the embed takes the scale of the parent window and matches it nicely.

More complicated is fetching/notifying of runtime changes, either by the user changing the scale factor while the UI is open (through the system or the host) or by moving the UI into a screen that has a different scale factor. Apparently some people are crazy enough to have such setups :/

Just getting the scale factor from the window we are meant to embed into helps though, it is a start.

**Comment by drobilla** [comment]
What window systems have a concept of per-window scale factor?  Regardless, if Pugl had a scale factor accessor API that worked "correctly" (whatever that means), then you wouldn't need it for that.

My thinking is basically: the only use of the parent window is to use the platform-specific API with it, so if you're going to do that, you might as well use the platform-specific API to get it as well.  Which is more annoying.  Which is good, because you probably shouldn't be doing that ;)

Re: changing scale factor, I think it should be part of `PuglConfigureEvent` for that reason.  Possibly also flags for fullscreen or (whatever future thing) should be in there, too.  The configure event should describe everything you need to know your place on the screen and how to draw to it properly etc.  This would make a `puglGetScaleFactor` type API kind of redundant, really.  Perhaps a `puglGetConfiguration` that returns the last configure would be a handy way to get <whatever position/size/scale/etc> without API spam, but the app can do that itself easily enough.

No idea how to actually implement dynamically changing scale factor on any of the platforms, though I do have laptops ad a much larger external display, so should be able to test it.

**Comment by falkTX** [comment]
> My thinking is basically: the only use of the parent window is to use the platform-specific API with it, so if you're going to do that, you might as well use the platform-specific API to get it as well. Which is more annoying. Which is good, because you probably shouldn't be doing that ;)

Well, not doing it results in the plugin UI look tiny if user has 200% display scale.
Situation is a bit tricky though. This info is not needed on Windows or Linux for LV2, VST2 or VST3, maybe more, since the host reports to the plugin what scale factor to use.
Plugins still need it if running standalone or in non-embed fashion.
On the other hand, macOS seems to be very special for this for plugins. Somehow hosts always skip reporting scale factor to plugins on macOS, assuming the plugin just uses native APIs to fetch that info instead. Perhaps because unlike other systems, macOS has proper APIs for it.

In any case, I am fine with this not being part of pugl and handle it myself, but I expect regular non-dpf devs to come back and ask for a similar thing once users report weird/tiny plugin UI sizes.

**Comment by drobilla** [comment]
I have no issue with exposing a scale factor.  Although IMO it's a stupid system (and the transition to high DPI was a complete disaster), it's nearly universal on modern systems and code needs to get at it to draw at a reasonable size.

I just see no reason to expose the parent window.

**Comment by drobilla** [comment]
Added in fdd6de0d

Please open a separate issue for the parent thing, if there turns out to be a need for it (outside of portability glue code that should ideally be in Pugl itself).
