### ISSUE TITLE
Bad mouse buttons on Mac

### ISSUE THREAD

**Issue by jpcima** [lv2/pugl#71]
The button info given by mouse events inverts right and middle.

Normal left-middle-right values: 1-2-3
Mac values: 1-3-2

**Comment by drobilla** [comment]
Hm.  Now that I look at it, I'm not sure which it should be.  The right button as button 2 seems to be a pretty widespread convention.  MacOS of course, but judging by a quick skim of their documentation, both glfw and SDL do as well.  Meanwhile the 1-2-3 convention is in X11 and glut, and what browsers use for MouseEvent.button.  They weirdly use the 1-3-2 order for MouseEvent.buttons though, so the mask that you would think is an AND of `1 << button` isn't.  Okay then...

:shrug:

The glfw thing carries a lot of weight to me, since that's by far the closest thing to pugl, and where cross-porting is most likely to happen.

**Comment by falkTX** [comment]
Speaking of glfw, I recently began porting some glfw stuff to pugl and needed to invert those buttons on macOS otherwise it would behave incorrectly.
See https://github.com/DISTRHO/Cardinal/blob/main/src/CardinalUI.cpp#L522

**Comment by drobilla** [comment]
While we're at it, there's also a zero-based vs one-based argument to be had here I suppose.  I guess I'll just try to gather as much convention from very vaguely similar libraries.

Left, middle, right numbers:

X11: 1, 2, 3
SDL: 1, 2, 3 (I was apparently wrong above)
Gtk: 1, 2, 3

GLUT: 0, 1, 2

MacOS: 0, 2, 1
Unity: 0, 2, 1
GLFW: 0, 2, 1
SFML: 0, 2, 1

Qt: Uses only masks: 1, 4, 2 (so sort of half points for 0, 2, 1, I suppose)

Kinda leaning towards 0, 2, 1 now.  Zero as a sentinel doesn't seem useful here and 1-based anything is annoying.  This would of course break all existing pugl code, but now's the time for that sort of thing...

**Comment by falkTX** [comment]
fwiw I am fine with anything, as long as those get defined in a header file.
the main issue right now is that there is no way to know until we try in each OS.

**Comment by drobilla** [comment]
Fixed in 6ca68635

I also added support for buttons 3 and 4 (back and forward usually) on Windows, which was missing earlier.  I don't know how to do even more buttons there, but Five Ought To Be Enough For Anybody™
