### ISSUE TITLE
Last release was in 2014. Maybe it's time for a new release?

### ISSUE THREAD

**Issue by yurivict** [lv2/pugl#94]

**Comment by drobilla** [comment]
?

There has never been a pugl release.

**Comment by yurivict** [comment]
Click on Tags.

**Comment by sjaehn** [comment]
Then, you made the tags (up to v0.3.0) by accident? Do you think about versioning and "official" releases in the future?

**Comment by drobilla** [comment]
Read the README.

A release happens when I'm confident that the API can remain stable for a good while... not when people nag me, as if I'm somehow unaware of this (again, prominently documented) situation.

Tickets are for issues that may be unknown, or risk being forgotten.  If you want to tell me what to do, feel free to contact me privately to discuss rates.

**Comment by drobilla** [comment]
Junk tags that, as far as I know, only existed on this mirror and don't correspond to any releases that actually exist anywhere have all been removed.
